# Generated by Django 4.1.1 on 2022-10-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoListApp', '0002_taskform_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskform',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
